from .plots.plot_monthly_profit import plot_monthly_profit
from .plots.plot_profit_by_unit import plot_profit_by_unit
from .plots.plot_profit_region import plot_profit_by_region
from .plots.plot_profit_by_client import plot_profit_by_client
from .plots.plot_monthly_margin import plot_monthly_margin
from .plots.plot_revenue_vs_profit_by_region import plot_revenue_vs_profit_by_region
from .plots.plot_top_bottom_unit import plot_top_bottom_unit
from .plots.plot_heatmap_unit_region import plot_heatmap_unit_region